server:
  port: "8080"
  debug: true

bucket:
  -
    name: "forum"
    type: "local"
    path: "/forum"
  -
    name: "wjh"
    type: "local"
    path: "/wjh"
  -
    name: "test"
    type: "s3"
    target: "minio"
    bucketName: "test"  # 请确保该 bucket 已存在

s3: # 此处可挂载多个 S3 连接
  -
    name: "minio"
    endpoint: "http://127.0.0.1:9000"
    accessKeyId: "YOUR_ACCESS_KEY"
    secretAccessKey: "YOUR_SECRET_KEY"
    region: "cn"  # 如果不知道就随便填
    useSSL: false
    usePathStyle: true  # 参考服务商设置

oss:
  limit: 10  # 文件大小限制 单位: MB
  adminKey: ""  # 管理员密钥

log:
  disableStacktrace: false # 是否禁用堆栈跟踪
  level: "info"            # 日志级别 debug调试 info信息 warn警告 error错误 dpanic严重 panic恐慌 fatal致命
  name: "oss"              # 日志名称
  writer: "all"            # 日志输出方式（console, file 或 all）
  loggerDir: "./logs"      # 日志目录
  logMaxSize: 10           # 单个日志文件最大大小 单位: MB
  logMaxAge: 7             # 日志保留天数
  logCompress: false       # 是否压缩日志文件